# Generated by Django 4.1.3 on 2022-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurment',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measure',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='measurement.measurment'),
            preserve_default=False,
        ),
    ]
