# Generated by Django 4.1.3 on 2022-12-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_measurment_sensor_id_sensor_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measure',
        ),
        migrations.AddField(
            model_name='measurment',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
